services:
  backend:
    build: ./backend
    container_name: rivezli-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: rivezli-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped